[2025-09-16T14:02:30.503+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T14:02:30.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nightly_retrain_als.tune_and_save scheduled__2025-09-15T00:15:00+00:00 [queued]>
[2025-09-16T14:02:30.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nightly_retrain_als.tune_and_save scheduled__2025-09-15T00:15:00+00:00 [queued]>
[2025-09-16T14:02:30.523+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-16T14:02:30.530+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): tune_and_save> on 2025-09-15 00:15:00+00:00
[2025-09-16T14:02:30.535+0000] {standard_task_runner.py:64} INFO - Started process 97 to run task
[2025-09-16T14:02:30.539+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'nightly_retrain_als', 'tune_and_save', 'scheduled__2025-09-15T00:15:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/nightly_retrain.py', '--cfg-path', '/tmp/tmpewvo09_6']
[2025-09-16T14:02:30.542+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask tune_and_save
[2025-09-16T14:02:30.574+0000] {task_command.py:426} INFO - Running <TaskInstance: nightly_retrain_als.tune_and_save scheduled__2025-09-15T00:15:00+00:00 [running]> on host 9bc3ef312961
[2025-09-16T14:02:30.620+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nightly_retrain_als' AIRFLOW_CTX_TASK_ID='tune_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T00:15:00+00:00'
[2025-09-16T14:02:30.621+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T14:02:30.629+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-16T14:02:30.630+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nset -euo pipefail\ncd "/opt/airflow/repo"\ndocker compose run --rm \\\n  -e SPARK_DRIVER_MEMORY=2g \\\n  app bash -lc \'\npython -m src.models.tune_als \\\n  --ratings_csv data/working/ratings_merged.csv \\\n  --model_out models/als_best \\\n  --ranks 16,32,64 \\\n  --regParams 0.01,0.05,0.1 \\\n  --maxIter 15 \\\n  --sims_topN 30 \\\n  --sims_method driver \\\n  --driver_batch 256 \\\n  --shuffle_partitions 32\n\'']
[2025-09-16T14:02:30.637+0000] {subprocess.py:86} INFO - Output:
[2025-09-16T14:02:31.163+0000] {subprocess.py:93} INFO -  Network repo_default  Creating
[2025-09-16T14:02:31.207+0000] {subprocess.py:93} INFO -  Network repo_default  Created
[2025-09-16T14:02:31.226+0000] {subprocess.py:93} INFO - time="2025-09-16T14:02:31Z" level=warning msg="Docker Compose is configured to build using Bake, but buildx isn't installed"
[2025-09-16T14:02:31.423+0000] {subprocess.py:93} INFO - #0 building with "default" instance using docker driver
[2025-09-16T14:02:31.423+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:31.424+0000] {subprocess.py:93} INFO - #1 [app internal] load build definition from Dockerfile
[2025-09-16T14:02:31.424+0000] {subprocess.py:93} INFO - #1 transferring dockerfile: 526B done
[2025-09-16T14:02:31.424+0000] {subprocess.py:93} INFO - #1 DONE 0.0s
[2025-09-16T14:02:31.424+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:31.424+0000] {subprocess.py:93} INFO - #2 [app internal] load metadata for docker.io/library/python:3.10-slim-bookworm
[2025-09-16T14:02:31.425+0000] {subprocess.py:93} INFO - #2 DONE 0.1s
[2025-09-16T14:02:31.425+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:31.425+0000] {subprocess.py:93} INFO - #3 [app internal] load .dockerignore
[2025-09-16T14:02:31.425+0000] {subprocess.py:93} INFO - #3 transferring context: 167B done
[2025-09-16T14:02:31.425+0000] {subprocess.py:93} INFO - #3 DONE 0.0s
[2025-09-16T14:02:31.536+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:31.537+0000] {subprocess.py:93} INFO - #4 [app 1/6] FROM docker.io/library/python:3.10-slim-bookworm@sha256:e7eed6c2e7fd1ecc43f0a37da7a115f4c9c9f50f247e9cba086c2f4583412fd9
[2025-09-16T14:02:31.538+0000] {subprocess.py:93} INFO - #4 resolve docker.io/library/python:3.10-slim-bookworm@sha256:e7eed6c2e7fd1ecc43f0a37da7a115f4c9c9f50f247e9cba086c2f4583412fd9 0.0s done
[2025-09-16T14:02:31.538+0000] {subprocess.py:93} INFO - #4 DONE 0.0s
[2025-09-16T14:02:31.539+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:31.539+0000] {subprocess.py:93} INFO - #5 [app internal] load build context
[2025-09-16T14:02:36.560+0000] {subprocess.py:93} INFO - #5 transferring context: 144.43MB 5.1s
[2025-09-16T14:02:41.624+0000] {subprocess.py:93} INFO - #5 transferring context: 204.53MB 10.2s
[2025-09-16T14:02:43.088+0000] {subprocess.py:93} INFO - #5 transferring context: 225.63MB 11.5s done
[2025-09-16T14:02:43.089+0000] {subprocess.py:93} INFO - #5 DONE 11.6s
[2025-09-16T14:02:43.089+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:43.089+0000] {subprocess.py:93} INFO - #6 [app 4/6] COPY requirements.txt .
[2025-09-16T14:02:43.089+0000] {subprocess.py:93} INFO - #6 CACHED
[2025-09-16T14:02:43.090+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:43.090+0000] {subprocess.py:93} INFO - #7 [app 2/6] RUN apt-get update &&     apt-get install -y --no-install-recommends         openjdk-17-jre-headless curl ca-certificates procps         libopenblas0 libgfortran5 &&     rm -rf /var/lib/apt/lists/*
[2025-09-16T14:02:43.090+0000] {subprocess.py:93} INFO - #7 CACHED
[2025-09-16T14:02:43.090+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:43.090+0000] {subprocess.py:93} INFO - #8 [app 3/6] WORKDIR /app
[2025-09-16T14:02:43.090+0000] {subprocess.py:93} INFO - #8 CACHED
[2025-09-16T14:02:43.091+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:43.091+0000] {subprocess.py:93} INFO - #9 [app 5/6] RUN pip install --no-cache-dir --upgrade pip &&     pip install --no-cache-dir -r requirements.txt
[2025-09-16T14:02:43.091+0000] {subprocess.py:93} INFO - #9 CACHED
[2025-09-16T14:02:43.091+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:43.091+0000] {subprocess.py:93} INFO - #10 [app 6/6] COPY . .
[2025-09-16T14:02:47.481+0000] {subprocess.py:93} INFO - #10 DONE 4.4s
[2025-09-16T14:02:47.645+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:47.645+0000] {subprocess.py:93} INFO - #11 [app] exporting to image
[2025-09-16T14:02:47.646+0000] {subprocess.py:93} INFO - #11 exporting layers
[2025-09-16T14:02:55.368+0000] {subprocess.py:93} INFO - #11 exporting layers 7.9s done
[2025-09-16T14:02:55.371+0000] {subprocess.py:93} INFO - #11 exporting manifest sha256:65c21379faaa01e552044fc9a819762988a1c6d96c4f1c0cd9bf91fe230c435b
[2025-09-16T14:02:55.569+0000] {subprocess.py:93} INFO - #11 exporting manifest sha256:65c21379faaa01e552044fc9a819762988a1c6d96c4f1c0cd9bf91fe230c435b done
[2025-09-16T14:02:55.569+0000] {subprocess.py:93} INFO - #11 exporting config sha256:b3fceccd30ea57c19da50d806c295acb0b6cac0b8542c77ad0cd2caa6510a5e5 done
[2025-09-16T14:02:55.570+0000] {subprocess.py:93} INFO - #11 exporting attestation manifest sha256:901774af1dd645dcc646a494a19553415db3bdb37a0024a264b13f9b4710cde6 0.0s done
[2025-09-16T14:02:55.570+0000] {subprocess.py:93} INFO - #11 exporting manifest list sha256:2276afc85e7093cc570e084e40fb7da99e81f8f9ff8d186e36de2e347d0a1325 0.0s done
[2025-09-16T14:02:55.570+0000] {subprocess.py:93} INFO - #11 naming to docker.io/library/repo-app:latest done
[2025-09-16T14:02:55.570+0000] {subprocess.py:93} INFO - #11 unpacking to docker.io/library/repo-app:latest
[2025-09-16T14:02:57.849+0000] {subprocess.py:93} INFO - #11 unpacking to docker.io/library/repo-app:latest 2.4s done
[2025-09-16T14:02:58.049+0000] {subprocess.py:93} INFO - #11 DONE 10.4s
[2025-09-16T14:02:58.059+0000] {subprocess.py:93} INFO - 
[2025-09-16T14:02:58.059+0000] {subprocess.py:93} INFO - #12 [app] resolving provenance for metadata file
[2025-09-16T14:02:58.086+0000] {subprocess.py:93} INFO - #12 DONE 0.0s
[2025-09-16T14:02:58.087+0000] {subprocess.py:93} INFO - time="2025-09-16T14:02:31Z" level=warning msg="current commit information was not captured by the build" error="git was not found in the system: exec: \"git\": executable file not found in $PATH"
[2025-09-16T14:02:58.762+0000] {subprocess.py:93} INFO - Error response from daemon: mounts denied:
[2025-09-16T14:02:58.766+0000] {subprocess.py:93} INFO - The path /opt/airflow/repo is not shared from the host and is not known to Docker.
[2025-09-16T14:02:58.768+0000] {subprocess.py:93} INFO - You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
[2025-09-16T14:02:58.769+0000] {subprocess.py:93} INFO - See https://docs.docker.com/go/mac-file-sharing/ for more info.
[2025-09-16T14:02:58.781+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-16T14:02:58.794+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T14:02:58.868+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-16T14:02:58.883+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nightly_retrain_als, task_id=tune_and_save, run_id=scheduled__2025-09-15T00:15:00+00:00, execution_date=20250915T001500, start_date=20250916T140230, end_date=20250916T140258
[2025-09-16T14:02:58.931+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task tune_and_save (Bash command failed. The command returned a non-zero exit code 1.; 97)
[2025-09-16T14:02:58.962+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-16T14:02:59.049+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-16T14:02:59.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
